### ISSUE TITLE
[Feature] Provide reference to the zapped note in the transaction detail

### ISSUE THREAD

**Issue by alltheseas** [minibits-cash/minibits_wallet#101]
_what happens_

Sometimes I receive zap comments, along with zaps. In short form apps (e.g. damus) these are displayed in reference to a particular noteID, or neventID. In minibits I lose the context of the note being zap commented.

_suggestion_

Display in thransaction view, detailed transaction view the reference noteID, or neventID. along with a link via e.g. [njump](https://github.com/fiatjaf/njump)

**Comment by minibits-cash** [comment]
Hi, this can be done.

Note to self: requires to extend lnurl server's claim api by zapRequest data as the wallet currently does not have them.

**Comment by minibits-cash** [comment]
Released for testing in 0.1.8-beta.65. Opens in njump.me.
