### ISSUE TITLE
Mint could not return signatures for this transaction

### ISSUE THREAD

**Issue by mdc2012** [minibits-cash/minibits_wallet#104]
Trying to send a zap in Amethyst connected to Minibits. Getting the error "The mint could not return signatures necessary for this transaction".

**Comment by minibits-cash** [comment]
Do you see transaction with error status in minibits then? If so, please provide audit trail from such tx detail, where more error details should be logged. Thnx!

**Comment by mdc2012** [comment]
Here is the most recent one. Token already spent.
My balance is about 28k sats.

[{"status":"DRAFT","mintBalanceToTransferFrom":{"mintUrl":"https://mint.minibits.cash/Bitcoin","balances":{"sat":28771}},"amountToTransfer":10,"unit":"sat","meltQuote":{"quote":"XKBvI7tIS_czWnTajF-grWtCCYq7wK716YQZSYDV","amount":10,"fee_reserve":2,"paid":false,"state":"UNPAID","expiry":1726452831,"payment_preimage":null,"change":null},"encodedInvoice":"lnbc100n1pnwvsklpp5597gtu22dc2au9uxe6uu9uwu27y9h7452d9xamhrnpw5km9qlh7shp5rzl9xgkunnxtxthctk0n85elhscjwsa3vrzyw0av9pw32kxhwdwscqzpuxqyz5vqsp5zsrg2nwdf9uzww68zzkjyzrjtgcwfwk2dgpfyw4nx2r4l7h76n4s9qxpqysgqde2f9cyrtkw9tn3hyfuuffs3nnn9ujrydcvyc053av44t9mpahy4hj2dj7zu50gje8jhsqyhsycvu95dlarscng49vvh3rhs59f6chsp0wl7yw","createdAt":"2024-09-15T02:13:56.083Z"},{"status":"ERROR","error":{"name":"MINT_ERROR","message":"The mint could not return signatures necessary for this transaction","params":{"message":"Token already spent.","mintUrl":"https://mint.minibits.cash/Bitcoin","caller":"WalletStore.sendFromMint","proofsToSendFrom":[{"id":"00500550f0494146","amount":512,"secret":"a16a677d9429c7d325569cc0dd65c2068194068a763ddf884ed5fed5fb51fa66","C":"0395390190e0e68fa1dee293642d1204ef86006acd334659297b62fbf82448922c","tId":30,"mintUrl":"https://mint.minibits.cash/Bitcoin","unit":"sat"}]}},"createdAt":"2024-09-15T02:13:58.637Z"}]

**Comment by minibits-cash** [comment]
Try to clean spent proofs from the wallet in Settings > Backup and recovery > Remove spent ecash.

As well make sure you run the latest update 0.1.8-beta.65

**Comment by mdc2012** [comment]
It reported no spent cash found, but worked ! Thanks so much, we can close
issue.

On Sunday, September 22, 2024, minibits-cash ***@***.***>
wrote:
> Try to clean spent proofs from the wallet in Settings > Backup and
recovery > Remove spent ecash.
>
> As well make sure you run the latest update 0.1.8-beta.65
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci3.googleusercontent.com/meips/ADKq_Nb7niwbh9vBtaB7-m-FGW4rscQHFr3Fee1oCqf6gnt9I7jGY36gv0dQhJYd1zU1-LBm7gU4oxbxEeJIlHJP7E0VqcSylrXJMOWjaFBW37kTFXy1GmccPOPQ3Z8xvDJZcOqJFgz9a73zB_MN0ww-nOL6dRt4QHbo3hIIh6IFfr6Q7nrHaqHEobz7GCwJ0Nns0MZrCajP80Bg1os8bs58Y3DIm-5NXoYtKnepaj4Uprykol1wUVrkVD4=s0-d-e1-ft#https://github.com/notifications/beacon/AJQDVV4PCMVV55E6MUY7NI3ZX4SO3A5CNFSM6AAAAABOGL2CX6WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTUNCTJ3Y.gif>Message
ID: ***@***.***>

**Comment by minibits-cash** [comment]
Keeping open, as there seems to be a bug in the information modal (shows no spent ecash found despite success). Thanks for reporting and testing.

**Comment by minibits-cash** [comment]
Fix for modal released in 0.1.9-beta.
