### ISSUE TITLE
Some transactions missing from list

### ISSUE THREAD

**Issue by slcw** [minibits-cash/minibits_wallet#116]
Minibits connected to Amethyst and Primal via NWC... 

When I zap someone, the transaction goes through successfully, but about half the time the transaction entry doesn't appear in my transaction log. And the transaction count at the top of the log says something like, "Showing 21 of 28 total", with the 7 transaction difference equaling the number of missing transactions. There doesn't appear to be any way to access those missing transactions.

Additionally, those transactions aren't being added to the NWC expenditure tally for each of my connected clients. According to the little NWC widgets on the main wallet screen, those missing transactions never happened even though they were successful zaps.

**Comment by minibits-cash** [comment]
Hi, do you have more then one mint that you've zapped from in the wallet?

**Comment by slcw** [comment]
I have 3 mints established: minibits.cash, utxo.one, and 0xChat.com. The zap send transactions that are listed are all linked to the utxo.one mint. I have no way of seeing which mints the missing transactions are linked to.

**Comment by minibits-cash** [comment]
I see. As the transactions are in the total counts they are not missing in the db. It is very likely a bug in the transaction selection that is shown on screen - they are selected and cached in wallet state grouped by mints to be shown that way on main screen, however need to be non-grouped and simply time sorted for the transaction list.

You should be eventually able to show missing ones by pressing Show more at the bottom of the list.

Will tag as a bug. Thanks for reporting.

**Comment by slcw** [comment]
I have tried clicking on the View More link at the bottom of the transaction list, but it never shows those transactions. I'll look forward to a fix in some future release. Thanks for addressing it! Much appreciated.

**Comment by minibits-cash** [comment]
Transaction history has been refactored in recent updates, there should not be a sorting issue / missing transactions anymore, pending more testing to be sure.
