### ISSUE TITLE
Amethyst NWC is unreliable

### ISSUE THREAD

**Issue by slcw** [minibits-cash/minibits_wallet#118]
I have NWC setup for both Amethyst and Primal, and the experience zapping from each of them is very different. Primal works great. Whenever I tap the zap button for a particular note, the zap always happens exactly as it should. However, zapping from Amethyst fails about half of the time, generating Minibits failure notifications.

Sometimes if I try again it works, but sometimes it just refuses to zap. If I switch back to Primal, I'm able to zap the same note right away with no problem. Not sure if this is a problem with Minibits, or with Amethyst, but given how popular Amethyst is I figure it's something you're going to want to address and resolve as soon as possible. Maybe coordinate with Vitor Pamplona on creating a solution.

**Comment by minibits-cash** [comment]
Please provide example of the failures you see. Is that an error popup visible in Amethyst? Or do you see Minibits push notifications with errors? If so, please find related error transaction inside the wallet and provide audit trail from tx detail.

Thanks!

**Comment by slcw** [comment]
The errors are Minibits push notices followed by a corresponding Amethyst error, both reporting that the zap attempt failed. Instead of getting the Minibits push notification reporting a successful zap payment, it's an error telling me that the send failed. The next time it happens I will record the specific language used in the error notice and pass it on. I foolishly cleared the error transactions from my Minibits ledger (blame my OCD) so I'll have to wait until it happens again to get that data. But I will update this thread as soon as I do.

**Comment by slcw** [comment]
I consolidated my sats into one mint (minibits) and deleted the others so minibits is my only mint. Since I did that, everything has been working perfectly. Zaps are going through properly on both Primal and Amethyst, and the transactions are displayed in my transaction log. Additionally, my NWC widgets are visible and properly showing my daily zap tally.

For whatever reason, it seems the problem is related to using multiple mints.

**Comment by minibits-cash** [comment]
Checked the implementation, currently could not grasp the reason why having multiple mints could interfere with nwc zaps (logic is that a mint with highest sats balance is used by default).

Please monitor and reopen this issue if you can catch the error transaction.

Thank you!

**Comment by slcw** [comment]
I don't think it's interfering with NWC specifically. I think the problem, which I suspect is rooted in having multiple mints, is causing the problem of transactions not properly displaying in the transaction log. And if they're NWC transactions, then it's also causing the little NWC widget not to accurately reflect associated zap transactions. I think the issue with Amethyst zaps intermittently failing is seperate. But that's just a speculative guess based on what I'm seeing on my end.

**Comment by minibits-cash** [comment]
Yeah, we'll deal with the bug related to transactions selection / sorting with multiple mints in #116
