### ISSUE TITLE
[Contacts] Keyboard won't show up again after cancelling creation of "own name"

### ISSUE THREAD

**Issue by deerwhisper2310** [minibits-cash/minibits_wallet#12]
When attempting to set my contact name, if I type something, hit check, then cancel, I can no longer type in the text box. I must go to a different screen and then return to "own name" to enable typing again

**Comment by minibits-cash** [comment]
Thanks for your report! Will look at it.

**Comment by minibits-cash** [comment]
Fixed in v0.0.8-alpha3.
