### ISSUE TITLE
Balance off because of Pending Ecash transactions sent.

### ISSUE THREAD

**Issue by ReichardKonige** [minibits-cash/minibits_wallet#121]
Hi I've been testing this walet between cashu.me web wallet and minibits android app (0.1.10-beta.2) using the same mint Minibit. It's fairly buggy on wallet balance. One specific issue I often see is when I send ecash that is then claimed by the cashu wallet. The transaction rarely show up as completed in the Minibits wallet. This causes the balance to be wrong since you don't have an "available" balance number under the main to show pending transactions. Perhaps add this. The reverse transaction of ecash from cashu.me to minibits always appears to complete normally. No hung transactions. For the minibits to cashu.me stuck pending transactions I clear it with Settings > Backup and recovery > Remove spent ecash. I'm not sure if that checks the ecash or if it just tags all pending as spent. Perhaps have that run automatically or add a refresh button to the main or transaction screen ?

I can repeat this behavior constantly. Minibits to Cashu.me always seem to stay as pending.

**Comment by minibits-cash** [comment]
Thank you for reporting. I was able to simulate the issue and there is indeed a regression bug introduced with recent changes.

It causes that pending proofs that change their status to spent lose reference to the transaction they belong to.

Will work on that and fix it.
It should not cause any loss of ecash in the meantime.

Will provide more info on how to clear already impacted transactions alongside I publish the fix.

Thanks for reporting!

**Comment by minibits-cash** [comment]
There is an over-the-air update with the fix available.
To clean stuck pending transactions please do the following - make sure that you DO NOT have valid pending transaction at the time:
1. Settings > Developer options > Force delete pending
2. Settings > Developer options > Resync transactions
3. Settings > Recovery > Remove spent ecash
4. Restart the wallet

**Comment by ReichardKonige** [comment]
Seems to be working fine now. sends back and forth from cashu.me work. It doesn't seem to update right away with shopstr but they don't support the new cashuB format and I send a old format cashuA token available from the ecash send screen. It did update after a few receives from other wallets/same mint later.
