### ISSUE TITLE
Recieve Transaction failed

### ISSUE THREAD

**Issue by Ypout** [minibits-cash/minibits_wallet#126]
I tried to recieve a transaction earlier today, it originally showed as draft, when I 'Retried to receive' it showed a 'Recieve Failed , token already spent'  Error. The status now  shows as  'ERROR'. 
![Screenshot_20241212_195407_Minibits](https://github.com/user-attachments/assets/a236547c-a935-45cc-83c3-483c0bc34bdb)

I'm not sure what information would be helpful to you.

Hers a copy of the audit trail:
[{"status":"DRAFT","amountToReceive":28483,"unit":"sat","createdAt":"2024-12-12T07:00:17.767Z"},{"status":"ERROR","error":{"name":"MINT_ERROR","message":"Token already spent.","params":{"caller":"WalletStore.receive"}}}]

I contacted the sender, they say the payment has been confirmed via lighting at their end.

Any help appreciated, thanks.

**Comment by biotq23DE** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Minibits Wallet Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> I tried to recieve a transaction earlier today, it originally showed as draft, when I 'Retried to receive' it showed a 'Recieve Failed , token already spent' Error. The status now shows as 'ERROR'. ![Screenshot_20241212_195407_Minibits](https://private-user-images.githubusercontent.com/191456917/395095112-a236547c-a935-45cc-83c3-483c0bc34bdb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTY4MDksIm5iZiI6MTczMzk5NjUwOSwicGF0aCI6Ii8xOTE0NTY5MTcvMzk1MDk1MTEyLWEyMzY1NDdjLWE5MzUtNDVjYy04M2MzLTQ4M2MwYmMzNGJkYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwOTQxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2FhMWYxNDY1YzAzODAzNzQxMzc2MWY5NTEyMjcxZTUxNmVhMzVhYWYyNDQ1ZWQwZjdkMmRlMjg1Y2I5MzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wJ-vYa0xB3SBA21WaSMdBLPq8Sb0Q1NrBgRzip2bo58)
> 
> I'm not sure what information would be helpful to you.
> 
> Hers a copy of the audit trail: [{"status":"DRAFT","amountToReceive":28483,"unit":"sat","createdAt":"2024-12-12T07:00:17.767Z"},{"status":"ERROR","error":{"name":"MINT_ERROR","message":"Token already spent.","params":{"caller":"WalletStore.receive"}}}]
> 
> I contacted the sender, they say the payment has been confirmed via lighting at their end.
> 
> Any help appreciated, thanks.

**Comment by borjasdee** [comment]
A complaint has be lodged and ticket has been created for you (Ticket number #MN736373)
Visit the official website to initiate a chat with the support team via [Minibits Wallet Live chat](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generate for you to properly rectify your problem

**Comment by Toshmach** [comment]
Hello @Ypout , 
It seems you’re encountering an issue with a transaction showing as "ERROR" after initially displaying as "draft" and failing upon retry with the message "Receive Failed, token already spent."

This could be due to a conflict or discrepancy in the transaction’s status within the system. I recommend contacting the support team for assistance. A support ticket has been created for you with ID MNW7638.

Visit [Minibits Wallet dApps Support Requests](https://thedappsupport.com/) and use the live chat bubble in the bottom-right corner to connect with an agent for help resolving this issue.

Thank you for your patience—I’m confident this will be resolved soon!

**Comment by minibits-cash** [comment]
Hi was that a transaction sent to your lightning address or did you receive it as ecash?

Thanks!

PS: there was a scammer comment I've just deleted.

**Comment by Ypout** [comment]
Thanks for the response. It was sent as a lighting payment, I have successfully received payments from tbe same sender before, without issue.  I've had three scam responses, it's nice to get proper one!

**Comment by minibits-cash** [comment]
I am quite sure it was paid, ecash would not come to your wallet otherwise.

Did not you copy the ecash token from token tracing section at the dcreen bottom while the transaction was stuck in DRAFT and received it in a separate transaction? The subsequent error returned by the mint on retry would be the same what you'd got.

Eventually try to do that now and write me the result.

**Comment by minibits-cash** [comment]
As well please send me your lightning address to support [at] minibits.cash, to be sure it was ok on lightning side and to check for other potential causes.

**Comment by Ypout** [comment]
I have just tried to recieve the transaction by copying the token tracking output and pasting it as a new ecash token receive transaction, but it gives the same 'token already spent' Error.  I had not tried this before. I did copy it into my original github post but deleted it before posting. My lighting address is ypout@minibits.cash. Thanks again  for your support.

**Comment by minibits-cash** [comment]
Please use your seed phrase to recover the balance including the received payment.

1. Copy your seed phrase
2. Factory reset wallet in Developer options
3. Go into Recover lost wallet from last onboarding screen, enter seed phrase recovery
4. Paste your seed, add your mint(s)
5. Start recovery, you might need to go through multiple rounds to get to unspent ecash, depending on wallet history

**Comment by Ypout** [comment]
Hi, thanks for the instructions.  I was able to recover the ecash including
the original failed transaction. Thanks for the Chrismas present.   What's
the best way to make a donation to the project?

**Comment by minibits-cash** [comment]
1. You can book a custom wallet address in the wallet for a donation, tap profile icon and than change address
2. Or you can send few sats as an ecash or with lightning to minibits [at] minibits.cash.

Thank you very much and Merry Christmas!

**Comment by Ypout** [comment]
Hi,

A lighning transaction was sent to the mint earlier today, but it does not
show up in my transaction history or as a pending transaction.  I tried to
create a new lighting invoice to test my wallet, but the app hangs creating
the invoice. I then tried to view the mint information from the manage
mints page and that failed too.

Any ideas?

Cheers

Clive
