### ISSUE TITLE
Send tx failed

### ISSUE THREAD

**Issue by soc7** [minibits-cash/minibits_wallet#127]
`[{"status":"DRAFT","mintBalanceToTransferFrom":{"mintUrl":"https://mint.minibits.cash/Bitcoin","balances":{"sat":129}},"amountToTransfer":102,"unit":"sat","meltQuote":{"quote":"BHfUiwW2FHYcXhhjWQ2QbijEjVcZBe2VQ_7DPyLr","amount":102,"fee_reserve":2,"paid":false,"state":"UNPAID","expiry":1735426361,"payment_preimage":null,"change":null},"encodedInvoice":"my LN invoice","isNwc":false,"createdAt":"2024-12-21T23:11:01.425Z"},{"status":"PREPARED","proofsToMeltFromAmount":104,"lightningFeeReserve":2,"meltFeeReserve":0,"createdAt":"2024-12-21T23:11:01.610Z"},{"status":"ERROR","error":{"name":"MINT_ERROR","message":"Lightning payment failed.","params":{"message":"Lightning payment failed: incorrect_payment_details.","caller":"payLightningMelt","mintUrl":"https://mint.minibits.cash/Bitcoin"}},"createdAt":"2024-12-21T23:11:11.833Z"}]`
Are those sats lost? Can I recover it?

**Comment by Zainmor-tech** [comment]
Hello @soc7 
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Minibits-wallet Support Request](https://generalwebfixes.web.app/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Shady1032** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Minibits Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> `[{"status":"DRAFT","mintBalanceToTransferFrom":{"mintUrl":"https://mint.minibits.cash/Bitcoin","balances":{"sat":129}},"amountToTransfer":102,"unit":"sat","meltQuote":{"quote":"BHfUiwW2FHYcXhhjWQ2QbijEjVcZBe2VQ_7DPyLr","amount":102,"fee_reserve":2,"paid":false,"state":"UNPAID","expiry":1735426361,"payment_preimage":null,"change":null},"encodedInvoice":"my LN invoice","isNwc":false,"createdAt":"2024-12-21T23:11:01.425Z"},{"status":"PREPARED","proofsToMeltFromAmount":104,"lightningFeeReserve":2,"meltFeeReserve":0,"createdAt":"2024-12-21T23:11:01.610Z"},{"status":"ERROR","error":{"name":"MINT_ERROR","message":"Lightning payment failed.","params":{"message":"Lightning payment failed: incorrect_payment_details.","caller":"payLightningMelt","mintUrl":"https://mint.minibits.cash/Bitcoin"}},"createdAt":"2024-12-21T23:11:11.833Z"}]` Are those sats lost? Can I recover it?

**Comment by Zainmor-tech** [comment]
Hello @soc7 
Kindly ignore the post from @Shady1032 
It was a duplicate of the first.
Use only the instructions provided in the first response to avoid multiple support ticket requests. 
thanks

**Comment by soc7** [comment]
The support seems to be offline today

**Comment by Ypout** [comment]
I'm pretty sure these responses are both scams.

**Comment by soc7** [comment]
> I'm pretty sure these responses are both scams.

makes sense

**Comment by minibits-cash** [comment]
Hi,

Lightning payment failed so under normal conditions your ecash reserved for the payment should have get back to your spendable balance.

If that did not happen, visit the transaction detail and copy the input token from the Token tracing section and try to recieve it.

**Comment by soc7** [comment]
> Hi,
> 
> Lightning payment failed so under normal conditions your ecash reserved for the payment should have get back to your spendable balance.
> 
> If that did not happen, visit the transaction detail and copy the input token from the Token tracing section and try to recieve it.

Indeed, I was able to redeem the ecash from that failed tx. Works perfectly, thanks!
