### ISSUE TITLE
UI: Contacts > New does not close if keyboard is minimized

### ISSUE THREAD

**Issue by callebtc** [minibits-cash/minibits_wallet#15]
The "Add new contact" dialog remains "maximized" after the user minimizes the keyboard. Might consider pulling it down or closing it.
![telegram-cloud-photo-size-2-5195216184277062352-y](https://github.com/minibits-cash/minibits_wallet/assets/93376500/6c24ce9e-0852-46bd-9595-9021a0c4f6cb)

**Comment by minibits-cash** [comment]
Yeah, I am just working on that one to add option to enter other then minibits.cash NOSTR addresses (as you can already replace wallet profile by your own). 

So I'll check if the modal I am using has the option to slide with keyboard to fix it.

**Comment by minibits-cash** [comment]
Sorry fix did not make it to the beta - there is a keyboardavoidingview related bug in react-native-modal if it does not cover full screen, so I will need to look for another option.

**Comment by minibits-cash** [comment]
Fixed in 0.1.3
