### ISSUE TITLE
[Wallet] Show balance of sats in USD/EUR/preferred currency

### ISSUE THREAD

**Issue by KraXen72** [minibits-cash/minibits_wallet#33]
- [ ] good ui & ux

**Comment by billerickson** [comment]
It would also be nice to be able to send a specific dollar amount and have it auto-convert to sats, like most lightning wallets.

**Comment by minibits-cash** [comment]
Released in 0.1.9-beta (limited to only USD and EUR to BTC rates)

**Comment by minibits-cash** [comment]
Duplicate to [#91](https://github.com/minibits-cash/minibits_wallet/issues/91)
