### ISSUE TITLE
Disable Automatic Clipboard Pasting

### ISSUE THREAD

**Issue by crimsonleaf363** [minibits-cash/minibits_wallet#38]
The current version of the app automatically pastes content from the clipboard when it is opened. 

### **Feature**

Introduce a toggle in the app's settings to enable or disable automatic clipboard pasting.

### **Benefit**

Users can choose whether they prefer the convenience of automatically pasting clipboard content.

**Comment by minibits-cash** [comment]
Thank you for your request.

As I am aware of, there is no automatic clipboard pasting as of now. Where used (tokens, urls, addresses) user needs to press the Paste button.

There is an empty stub function to read clipboard in WalletScreen.tsx, however it's used in dev only (tracing is available only in dev environment)

If you'd point out where such thing happens, please leave a comment, I'll fix that.

**Comment by minibits-cash** [comment]
Hi thank you for coming back with more detailed information.

I have just released over the air update for version 0.1.6 that removes reading of clipboard in WalletScreen.tsx. It might be that GrapheneOS tracks it and pops up the warning despite of the fact, that clipboard is not logged outside of development environment.

If so, you should stop to see the warning after updating to v0.1.6-beta.2. Please restart app or go to Settings screen to get the OTA update and report the result.

**Comment by crimsonleaf363** [comment]
After the latest update, I no longer see the pop-up message.
