### ISSUE TITLE
Copy mintUrl

### ISSUE THREAD

**Issue by FiliTol** [minibits-cash/minibits_wallet#41]
# Expected behaviour

I have some mints registered in my minibits wallet. I would like to copy the urlMint to give it to a friend. 
Going in Mint Info > Show should enable to copy the mintUrl.

# Actual behaviour

Mint Info > Show does not provide the possibility to copy the mintUrl.

**Comment by minibits-cash** [comment]
No problem, will add. As a workaround your friend might enjoy even more is to send him some ecash from that mint. When receiving, mint arrives to his wallet :)
