### ISSUE TITLE
"Reclaimed existing own profile" error when trying to claim Nostr address twice. 

### ISSUE THREAD

**Issue by terryyrret** [minibits-cash/minibits_wallet#42]
**Describe the bug**
When I try to change my Minibits wallet address to use my own Nostr profile I get this error.
![Screenshot_20240201-141740](https://github.com/minibits-cash/minibits_wallet/assets/152494081/6ff6d699-1abc-411e-9c35-58ae67229dac)
I have a feeling that I get this error because I have already in the past used my nostr key for a Minibits wallet address. But, I uninstalled the app, so I don't have access to that data. I got this error on a new fresh install of Minibits.

**To Reproduce
Steps to reproduce the behavior:**

1. Go to contacts
2. Click "Switch your wallet name and picture?"
3. Click "Change"
4. Click "Use own Nostr profile"
5. Fill in all the details
6. At the end, hit "Apply change"

**Comment by minibits-cash** [comment]
Thank you for your report, something is broken or at least not properly validated there - what an ugly error.

Do you still keep the seed from previously uninstalled app instance?

**Comment by minibits-cash** [comment]
OK I perhaps figured it out. Minibits supports to reclaim your own Nostr profile, e.g. after recovery. However, the logic did not cover the situation where you not only have had used that nostr address on previous install, as you pointed correctly, but likely changed as well nostr address linked to your keys.

There should be fixed release on the server, please retry and report the result.

As a side question: What is the use case for you to import your own nostr identity into the wallet? Why I am asking is, that in the meantime minibits.cash addresses have a neat feature to behave as Lightning addresses as well, thus enabling lightning payments to the address from most lightning wallets as well as receiving nostr zaps directly to the wallet (after adding it to your nostr profile lightning address field). These won't work after importing other nostr address. 

Of course all ecash transactions will continue to work just fine.

**Comment by terryyrret** [comment]
Sorry for the late reply. But, yeah, it works now. I was thinking of importing my Nostr key so that I could use my Nostr profile as my identity instead of the randomly generated identity. At least, that was the impression that I got from the UI. I on my Nostr client, Amethyst, that there were these machine generated profiles on Nostr with the minibits.cash domain for their NIP-05 id. So, I thought that ecash was being sent through DMs on nostr to the private key that was generated by the app for the randomly generated identity. I thought that if I put in my personal Nostr private key, then it would not use that generated profile, but instead would use my personal Nostr private key and scan my DMs for ecash and automatically redeem it in the wallet for me.

**Comment by minibits-cash** [comment]
First, glad the fix works.

Second, yes you've got it right - you should get received ecash tokens to the wallet and at the same time see them in your amethyst dms.

Just you will receive zaps to another wallet (if you have lightning address attached to your nostr profile).

Thanks for testing minibits!
