### ISSUE TITLE
"Select mint to top-up" doesn't scroll.

### ISSUE THREAD

**Issue by HamishMacEwan** [minibits-cash/minibits_wallet#45]
Only the first four mints can be seen and the list can't be scrolled.

![image](https://github.com/minibits-cash/minibits_wallet/assets/388061/fb5500b9-a247-40f2-a93f-c4db0bf9f5bb)

**Comment by minibits-cash** [comment]
Fix is available in recent update: v0.1.6-beta.5

**Comment by HamishMacEwan** [comment]
I'll get about updating to that.

If it can have more than one, it will, and the upper limit is then pretty high.

On behalf of multi-*s everywhere, thank you.
