### ISSUE TITLE
Error while melting tokens

### ISSUE THREAD

**Issue by upuzzled2** [minibits-cash/minibits_wallet#47]
![IMG_20240207_133618](https://github.com/minibits-cash/minibits_wallet/assets/68016579/e1838b40-ce4c-435b-973d-b52606bd89e3)
![IMG_20240207_133726](https://github.com/minibits-cash/minibits_wallet/assets/68016579/a45b9975-a2e2-4770-834a-d212d44866a6)

Since upgrade to 0.1.6-beta3 have been unable to pay lightning invoices generated in nostr.

**Comment by minibits-cash** [comment]
Please take some time, issue not related to wallet update.

Mint software has been upgraded to the new version and there is some bug that passed the tests mint devs need to inspect.

Affected are lnbits extension mints on 0.4.0 version.

All kinds of intra mint payments works, lightning payments from pure nutshell or older versions mint instances to minibits work, outgoing lightning payments fail.

Sorry for inconvenience.

**Comment by minibits-cash** [comment]
The mint.minibits.cash has been patched, I've tested that outgoing lightning payments work again.
