### ISSUE TITLE
Thanks for inviting me!

### ISSUE THREAD

**Issue by trbouma** [minibits-cash/minibits_wallet#5]
Not an issue, but I wanted to say thanks for inviting me! I have got the wallet downloaded and working. I have added my own mint. I successfully transferred some coins to my wallet, but then I started to get an exception when trying to scan and when trying to paste from memory. I haven't fully troubleshooted yet, but will update when I can specify more of the issue.

**Comment by trbouma** [comment]
I did a factory reset and everything seems to be working now.

**Comment by trbouma** [comment]
closing issue

**Comment by minibits-cash** [comment]
Thanks for testing, if something appears, just raise a new issue. As well please update to the latest version from app's Update manager, another important fix is there.
