### ISSUE TITLE
Not enough inbound liqidity followed by missing inbound transaction

### ISSUE THREAD

**Issue by chGoodchild** [minibits-cash/minibits_wallet#68]
- Minibits presented a notification that there wasn't enough inbound liquidity for an incoming transaction
- The incoming transaction failed
- Later a smaller inbound transaction disappeared. The funds are neither visible in the sending wallet (alby) nor in the receiving (mint.minibits.cash)
- Even later a small test zap also got stuck, but came through on the second try

Is the mint facing issues? How can these transactions be debugged?

**Comment by minibits-cash** [comment]
Hello, thank you for your report. Could you provide the audit trail of relevant transactions (you'll find it in transaction detail at the bottom) to grasp what and whose was the exact error shown. Thank you!

**Comment by chGoodchild** [comment]
Thanks for getting back to me :)

Here is the audit trail for the larger transaction:

```
[{"status":"DRAFT","amountToTopup":86000,"createdAt":"2024-05-07T13:55:10.367Z"},{"status":"PENDING","paymentRequest":{"type":"OUTGOING","status":"ACTIVE","mint":"https://mint.minibits.cash/Bitcoin","encodedInvoice":"lnbc860u1pnr5v4app5wel3pdk28z5qa4p8cu0upejwap9mtuf7gslaej4p2dttg44a6p6qdq2f38xy6t5wvcqzzsxqrpcgsp5wcx3n253tknzsqpggrnjd3ttegltv5zs0gftyk6pvg7y7dewdsfs9qyyssqnax95zrcsntn6kz5cm3u8y9v7796uy258vxpe2trpjhj324mtjxk4k87y9qwdxzrw08l0vp48gkuxeskc7hz9eeqfwre6tk7d9vf9jqp20celm","amount":86000,"description":"Phoenix ","paymentHash":"tixkbSYixaGUtZL_aSiQd8JfTmVoLJ0Kg2xnpxYa","contactFrom":{"pubkey":"941f1f030d086c62144a132e1a821a1205767fbe98e7970f7054395f2ef16409","npub":"npub1js037qcdppkxy9z2zvhp4qs6zgzhvla7nrnewrms2su47th3vsys0825vq","name":"chandran","nip05":"chandran@minibits.cash","picture":"https://api.minibits.cash/profile/avatar/941f1f030d086c62144a132e1a821a1205767fbe98e7970f7054395f2ef16409"},"expiry":1800,"transactionId":125,"expiresAt":1715091909000,"createdAt":1715090109000}},{"status":"EXPIRED","message":"Invoice expired before being paid.","createdAt":"2024-05-07T15:47:05.884Z"}]
```

Unfortunately I don't see any sign of the smaller LNURL transaction. 

I have attached a screenshot of a popup I get when updating the app. Not sure if the pop-up is related.. 

![signal-2024-06-16-17-22-41-086.jpg](https://github.com/minibits-cash/minibits_wallet/assets/1100745/f51d1d7e-63b2-4477-a060-3836477a6e0d)

Thanks for helping :)

**Comment by chGoodchild** [comment]
This must be the pre-image of the lightning payment from Alby to the mini-bits LNURL. 

The SATs don't show up in minibits or in Alby:

```
Preimage
9f7d14c232793ad5e27257dc39bd88dd6f87764550a47cc1ecf86a90cff0aeca
Payment Hash
57d0c600abdf239853f72d0e30a73a98ad1638376f9ae8ed19f0836993bc22ab
```

**Comment by minibits-cash** [comment]
Screenshot helped. Go to the Settings > Backup and recovery. Copy your seed first and then go through "Recover wallet address". It will reset profile data so that the claiming of payments recieved to lightning address resume to work.

**Comment by chGoodchild** [comment]
Thanks, LNURL payments are coming through again :)

Unfortunately the payment from a few weeks ago didn't arrive yet. Is it safe to assume that the SATs went back to the sender after two weeks?

**Comment by minibits-cash** [comment]
I'll check today the state of 86k invoice and come back.

**Comment by minibits-cash** [comment]
86k payment failed based on lightning node data, so sats remained in sender wallet.
![payment_lnd](https://github.com/minibits-cash/minibits_wallet/assets/138401554/5cc3146d-5bfa-4c72-b92e-5fd7d62bf062)

**Comment by chGoodchild** [comment]
So the SATs are with the mint now? 

A friend just tried melting from mini-bits to lightning from minibits and faced similar issues:

```
[{"status":"DRAFT","mintBalanceToTransferFrom":{"mintUrl":"https://mint.minibits.cash/Bitcoin","balances":{"sat":564824}},"amountToTransfer":550000,"unit":"sat","meltQuote":{"quote":"HxT3EPOfm9c_0HoVGDTGAPaPkB6_jFVwTHygvsh-","amount":550000,"fee_reserve":5500,"paid":false,"expiry":1720118509},"encodedInvoice":"lnbc5500u1pn8mvndpp5hl6wn5q0aej8ul9rf03pwhg9dhwlcgyamc8fes8v2effpy6cyz8scqpjsp5nnqgd0jf47frdlke0ngsvzw8zj9l0d6m5a0gkshtetnaty3h99jq9q7sqqqqqqqqqqqqqqqqqqqsqqqqqysgqdqqmqz9gxqyjw5qrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glclll9tcgsa40g75qqqqlgqqqqqeqqjqf6f63qs9cgqvmyhna9rvpnfruy2f9sywyvqxm4ldeuxuruycelc3l5h2mlxflp9z34w8zqmdsjdm8rltfq8h5ystedsfk70jupqnhpgpkyr03r","createdAt":"2024-06-27T18:42:04.179Z"},{"status":"PREPARED","createdAt":"2024-06-27T18:42:07.241Z"},{"status":"ERROR","error":{"name":"MINT_ERROR","message":"Lightning payment failed.","params":{"message":"Lightning payment unsuccessful. Payment failed: No route to destination.","caller":"payLightningMelt","mintUrl":"https://mint.minibits.cash/Bitcoin"}},"createdAt":"2024-06-27T18:42:20.163Z"}]

```

What's the safest way for them to recover their SATs?

**Comment by chGoodchild** [comment]
So the SATs are with the mint now?

**Comment by minibits-cash** [comment]
As 86k lightning payment did not complete, sats remained in sender wallet. Mint issues new ecash only against completed lightning payment.

**Comment by chGoodchild** [comment]
Ah sorry I didn't read your previous message correctly. I'll check with the sender ... Thanks :)
