### ISSUE TITLE
[Wallet] Unable to pay an invoice due zero estimated fee

### ISSUE THREAD

**Issue by iWarpBTC** [minibits-cash/minibits_wallet#7]
I'm on my own lnbits mint. Got an invoice from an another node for let's say 1500 sats. When scan it in Minibits I can see in my lnbits log theres a checkfees request (and I checked it returns 15 for this invoice), but there's 

> + estimated fee 0 sats

in the Minibits transfer screen. Transfer gonna fail because 

> Provided proofs (1500 sats) not enough for Lightning payment (1515 sats).

Minibits 0.0.5-alpha.4 (commit d395714)

**Comment by minibits-cash** [comment]
Thanks for report, looks definitely like a bug on Minibits. Will dig deeper and come back. Until the fix please do not test transfers to remote mints.

**Comment by minibits-cash** [comment]
There is a fix available for over-the-air update in wallet's Update Manager - [v0.0.5-alpha.6](https://github.com/minibits-cash/minibits_wallet/releases/tag/v0.0.5-alpha.6).

I will keep the issue open for now until few alpha testers confirm.

Thank you for your testing and reporting!

**Comment by iWarpBTC** [comment]
I had to force app restart for update to appear. After the update the issue is gone. Thanks for your work!

**Comment by minibits-cash** [comment]
Good to hear and thank you for your retest!
