### ISSUE TITLE
Custom nostr server removed after update 

### ISSUE THREAD

**Issue by GitKalle** [minibits-cash/minibits_wallet#71]
Hello,

after update from v0.1.7 beta 5 to v0.1.7 beta 12 my custom nostr server is not in the server list anymore.

Greets

**Comment by minibits-cash** [comment]
You mean nostr relay? Considering previous issue, I suppose your wallet state might be broken and this is how it manifests (as between 5 - 12 there were not changes to anything related to relays management)
