### ISSUE TITLE
[Recovery] Which keyset to choose?

### ISSUE THREAD

**Issue by GitKalle** [minibits-cash/minibits_wallet#72]
How does I know which keyset I have to choose during recovery? When there is a lag in my knowledge can you suggest a good explanation?

**Comment by minibits-cash** [comment]
Mint currently support legacy and new keyset format:

`{"keysets":[{"id":"9mlfd5vCzgGl","unit":"sat","active":true},{"id":"00500550f0494146","unit":"sat","active":true},{"id":"00827d7d75aa8fcb","unit":"sat","active":true},{"id":"ctv28hTYzQwr","unit":"sat","active":true}]}`

9mlfd5vCzgGl and ctv28hTYzQwr are legacy format, hex keysets are the same just in new format. So mint currently has 2 active keysets and formats are converted internally. If you made transactions recently, your ecash belongs to keyset 00500550f0494146 or ctv28hTYzQwr. Just select one of them. Try older one only if you could not recover whole balance with that one.
