### ISSUE TITLE
Transaction to custom LN address has an error

### ISSUE THREAD

**Issue by GitKalle** [minibits-cash/minibits_wallet#74]
I send a sat to my custom LN address and Minibits shows an error, see picture.

![IMG_20240518_133153](https://github.com/minibits-cash/minibits_wallet/assets/18066460/0645bdee-65a4-4b0a-bfb5-42147328c9ec)

What's the problem?

**Comment by minibits-cash** [comment]
Copy audit trail at the bottom and paste here please

**Comment by GitKalle** [comment]
> Copy audit trail at the bottom and paste here please

```javascript
[
  {
    "status": "DRAFT",
    "amountToReceive": 1,
    "unit": "sat",
    "encodedToken": "cashuAeyJ0b2tlbiI6W3sibWludCI6Imh0dHBzOi8vbWludC5taW5pYml0cy5jYXNoL0JpdGNvaW4iLCJwcm9vZnMiOlt7ImlkIjoiMDA1MDA1NTBmMDQ5NDE0NiIsImFtb3VudCI6MSwic2VjcmV0IjoiN2YvRnRNWmNONEs4Yy80amVsaXU4UEsrSzdjV2REVGtpZTZKS2RmTFlmST0iLCJDIjoiMDJlNjY3NGQxYmQyODczYTQwZWVjZjJmY2ZiODAxN2UwYzYxMzk3ZjE4YjU4ZDA4MDU3NjZjZDg5YWIwNDY5ZGE5In1dfV0sIm1lbW8iOiJUZXN0In0",
    "createdAt": "2024-05-18T12:06:54.287Z"
  },
  {
    "status": "ERROR",
    "error": {
      "name": "TypeError",
      "message": "Network request failed",
      "params": {}
    }
  }
]
```

**Comment by minibits-cash** [comment]
Trail shows, that your wallet correctly received the cashu token generated by the lightning address server on received payment. Subsequent wallet request sent to the mint to swap the token for fresh 1 sat ecash note failed for some reason.
Yet the error name logged is strange, should always get assigned MINT_ERROR. I've seen another such case, if it would appear again, please comment here.

Receiving payments sent to the lightning address will change completely in the next release, so I'll keep it as that for now.

**Comment by minibits-cash** [comment]
Much more clear now. Please go to the Backup and recovery. At the bottom, press "increase recovery indexes". Then retry.

**Comment by GitKalle** [comment]
> Much more clear now. Please go to the Backup and recovery. At the bottom, press "increase recovery indexes". Then retry.

Done. Got a message like "add 50 indexes.." but the error persists.

Audit trail:
```
[
  {
    "status": "DRAFT",
    "amountToReceive": 1,
    "unit": "sat",
    "encodedToken": "cashuAeyJ0b2tlbiI6W3sibWludCI6Imh0dHBzOi8vbWludC5taW5pYml0cy5jYXNoL0JpdGNvaW4iLCJwcm9vZnMiOlt7ImlkIjoiMDA1MDA1NTBmMDQ5NDE0NiIsImFtb3VudCI6MSwic2VjcmV0IjoiVGxBYTU3Zm9TbVJVSGU2MWlDU1E5eVFzQWRBZkh1WFI0L01HbkZXRzRFYz0iLCJDIjoiMDNlZjgyYmY5ZGY1YTMxNjlmZjFiMzAwNzM3Y2Q1ZDIwMjU0NWU4YWZkOTg2Y2I4Mjg4OWE5MDg3MWQyOWM1MjVmIn1dfV0sIm1lbW8iOiJNaW5pYml0cyJ9u",
    "createdAt": "2024-05-29T16:13:26.143Z"
  },
  {
    "status": "PREPARED",
    "errorToken": {
      "token": [
        {
          "mint": "https://mint.minibits.cash/Bitcoin",
          "proofs": [
            {
              "id": "00500550f0494146",
              "amount": 1,
              "secret": "TlAa57foSmRUHe61iCSQ9yQsAdAfHuXR4/MGnFWG4Ec=",
              "C": "03ef82bf9df5a3169ff1b300737cd5d202545e8afd986cb82889a90871d29c525f"
            }
          ]
        }
      ]
    },
    "updatedToken": {
      "token": []
    },
    "errors": [
      "Error: outputs have already been signed before."
    ],
    "createdAt": "2024-05-29T16:13:27.824Z"
  },
  {
    "status": "ERROR",
    "error": {
      "name": "MINT_ERROR",
      "message": "Mint returned error on request to swap the received ecash.",
      "params": {
        "caller": "receiveTask",
        "message": "Error: outputs have already been signed before.",
        "errorToken": {
          "token": [
            {
              "mint": "https://mint.minibits.cash/Bitcoin",
              "proofs": [
                {
                  "id": "00500550f0494146",
                  "amount": 1,
                  "secret": "TlAa57foSmRUHe61iCSQ9yQsAdAfHuXR4/MGnFWG4Ec=",
                  "C": "03ef82bf9df5a3169ff1b300737cd5d202545e8afd986cb82889a90871d29c525f"
                }
              ]
            }
          ]
        }
      }
    },
    "errorToken": {
      "token": [
        {
          "mint": "https://mint.minibits.cash/Bitcoin",
          "proofs": [
            {
              "id": "00500550f0494146",
              "amount": 1,
              "secret": "/MGnFWG4Ec=",
              "C": "03ef82bf9df5a3169ff1b300737cd5d202545e8afd986cb82889a90871d29c525f"
            }
          ]
        }
      ]
    }
  }
]
```

**Comment by minibits-cash** [comment]
Did you try to recover from seed before? If so (and you did not reach end of interval your previous ecash history reached) it might be necessary to move indexes much more ahead.

Your generated ecash is still refused by mint because in the past it has already seen the same proofs - generator increases this index counters to create a sequence that is than recoverable from seed.

In the mint info page, bottom section "local mint data" or so you can see if adding to indexes works - you should see it undet proofCounters data node.

So try to increase it well ahead and retry

**Comment by GitKalle** [comment]
Now it works. Thanks for help.
