### ISSUE TITLE
[Bug] Loss of funds after attempting a 999999sat payment

### ISSUE THREAD

**Issue by stevenwelsh565** [minibits-cash/minibits_wallet#81]
With the https://mint.minibits.cash/Bitcoin mint I attempted a 999999 sat payment. This lead to a MINT_ERROR, saying "Maximum melt amount is 1000000 sat." But my coins never were returned to my wallet.

How can I recover them?

**Comment by minibits-cash** [comment]
Together with fee reserve the payment hit the mint limit. Please copy me the errored transaction audit trail  to support@minibits.cash email, or using nostr to dev@minibits.cash. Do not post it publicly here.

**Comment by minibits-cash** [comment]
As a quick try you can restart the wallet under normal behavior it should try to sweep ecash from pending state back to spendable after failed lightning tx.

**Comment by stevenwelsh565** [comment]
I tried emailing `support@minibits.cash` from gmail and got this error:

```The recipient server did not accept our requests to connect. For more information, go to https://support.google.com/mail/answer/7720 [minibits.cash 2a01:4f8:c2c:bb96::2: timed out] [minibits.cash [195.201.20.134](http://195.201.20.134/): timed out]```

**Comment by minibits-cash** [comment]
Sorry I'll need to solve some unintended DNS related issues. In the meantime, please send it to bitango.app@gmail.com

**Comment by stevenwelsh565** [comment]
Done

**Comment by minibits-cash** [comment]
Thank you. Retested your scenario and found a bug where ecash returning after failed lightning payment from pending state back to spendable balance missed unit param, thus was not included into balances. Hotfix is on the way as an over the air update.

I think the easiest way to recover should be to go to Settings > Backup and recovery > Local recovery tool and reload the wallet from the local backup that sets the unit if missing in the process.

**Comment by stevenwelsh565** [comment]
Will the hotfix also handle my case? I'm not in a rush to get the funds
back so I'm happy to wait until it is available on google play.

**Comment by minibits-cash** [comment]
Hotfix prevents future cases to happen. To fix your existing ecash, follow the steps above.

Thanks for reporting the issue.

**Comment by stevenwelsh565** [comment]
Thanks. I tried using the "Local recovery tool", and clicked on "Recover to
wallet" While that screen showed 1038965 SATS as being present, the sats
still didn't show up in my wallet, even after reloading the app.

**Comment by minibits-cash** [comment]
Will require yet one small fix of too restrictive validation of backed up proofs, sorry. 

I'll write here when I'd release it. After update, you'd run local recovery again and it should pass.

**Comment by stevenwelsh565** [comment]
Sounds good! Let me know.

**Comment by minibits-cash** [comment]
Releasing fix in local recovery process as beta.28. On travel, so had not space to simulate whole process, please turn on debug level logging in developer options and retry to recover from local backup.

**Comment by stevenwelsh565** [comment]
Thanks! That fixed it.
