### ISSUE TITLE
Is the phone really online?

### ISSUE THREAD

**Issue by chGoodchild** [minibits-cash/minibits_wallet#84]
I find the offline mode really really useful. 

However, my phone thinks that its online when its connected to wifi and the router isn't giving my phone access to the internet gateway. 

The work around is easy: just turn off the wifi, copy an e-cash token in offline mode and turn the wifi back on. 

Its probably mostly my problem at this point so I'm happy to help solve the problem if needed.

**Comment by minibits-cash** [comment]
Hi, what's your use case to receive token in offline mode (i.e. do not swap it for fresh ecash immediately)?

**Comment by chGoodchild** [comment]
The WiFi router is selling me access to the internet. I give the router e-cash, it melts the e-cash to lightning and it gives me internet access. 

Mini-bits has notes prepared for situations where the user doesn't have internet, so its perfect for my situation. However, the mini-bits UI doesn't present the notes to the user when the user is already connected to the WiFi router, but the user is still offline because he hasn't paid yet. 


https://njump.me/nevent1qqstmwkdmrjsf7zzk05yl3x8m7lkaahvll7jw22j59ku7fp5uvfr0qcpzamhxue69uhkzarvv9ejumn0wd68ytnvv9hxgtczyphydppzm7m554ecwq4gsgaek2qk32atse2l4t9ks57dpms4mmhfxqcyqqqqqqggjp56q
