### ISSUE TITLE
[Feature request] Option to add amount when you pay to LN address

### ISSUE THREAD

**Issue by Darth-Coin** [minibits-cash/minibits_wallet#90]
If I choose to pay to a LN address, it generate a LN invoice with the minimum amount set (1sat) and I do not have the option to set the amount, only a comment.

Please can you add the the option to set the amount of the invoice requested through LN address ?

**Comment by minibits-cash** [comment]
After entering lightning address / selecting it from contacts, default amount is set based on receiver's lightning address setting (often 1sat).

This amount is editable, preselectef and keyboard should show to allow overwriting it immediately.

Only on pressing Continue, invoice is generated. If you see other behavior, please post screenrecording and device model, thanks!
