### ISSUE TITLE
Amounts denominated in fiat currency

### ISSUE THREAD

**Issue by prusnak** [minibits-cash/minibits_wallet#91]
I would like to see my balance shown in fiat currency.

Also the send and receive dialogs should have an option to enter amount in fiat currency.

There is a free API available from https://yadio.io/api.html for example.

**Comment by minibits-cash** [comment]
Thanks for the issue, I understand the need. Technically not very complicated (just need to behave gracefully for offline use), however I think proper focus is needed for UX/UI.

For now I am thinking to include that into bigger redesign I plan once Minibits will support multi-mints payments, that would allow to present mint balances in less prominent way - and so may be give some space for additional data.

**Comment by minibits-cash** [comment]
Released in v0.1.9-beta. Currently provides rate conversion for a single selected currency, but will be expanded to more then one over some time.
