### ISSUE TITLE
Pending ecash doesn't show up again

### ISSUE THREAD

**Issue by f321x** [minibits-cash/minibits_wallet#94]
I had two pending lightning payments (used minibits to pay hold invoices), which should have been refunded to the wallet balance after some hours. But the tx/ecash was still shown pending after >24h.
Restoring the wallet from backup did fix this and the balance was correct again.
Maybe the wallet should automatically check on pending transactions from time to time?

**Comment by f321x** [comment]
Sent audit trail on Nostr👍

**Comment by minibits-cash** [comment]
Potential fix released in recent update.
