### ISSUE TITLE
npub.cash lightning addresses are too long for contact field

### ISSUE THREAD

**Issue by mariaa144** [minibits-cash/minibits_wallet#96]
When trying to enter a npub.cash lightning address I created from using cashu.me I noticed the address doesn't fit and is cut off. When I try to save I get a `VALIDATION_ERROR` because much of the address is missing I assume.
![IMG_20240825_074051](https://github.com/user-attachments/assets/8ce84c5d-b598-4f6f-b8a5-a0cc3641c3df)
![IMG_20240825_074915](https://github.com/user-attachments/assets/5b937eb7-86fd-4613-8676-0d9e9230f125)

**Comment by minibits-cash** [comment]
Released relaxed validation that should make npub.cash address fit.
