### ISSUE TITLE
Can't create e-cash string

### ISSUE THREAD

**Issue by chGoodchild** [minibits-cash/minibits_wallet#97]
I'm able to redeem ecash, but the wallet doesn't respond when I try to create ecash strings. 

Upon closing the wallet and reopening it, I get a "draft" entry in the wallet with the following audit trail:

```
[{"status":"DRAFT","mintBalanceToSendFrom":{"mintUrl":"https://mint.minibits.cash/Bitcoin","balances":{"sat":8979,"undefined":5}},"createdAt":"2024-08-25T20:34:10.548Z"}]
```

**Comment by minibits-cash** [comment]
There si likely still some ecash selection issue when preparing the tx (despite recent attempt ti fix)

To fix, please send your whole balance to yourself - as an ecash. Send it to your wallet address or just copy / paste to receive.

This will make the mint to swap your ecash for non problematic notes combibation.

**Comment by chGoodchild** [comment]
Thanks, it works now :)
